#!/bin/bash

curl -o /tmp/rl9.iso https://download.rockylinux.org/pub/rocky/9/isos/x86_64/Rocky-9.4-x86_64-boot.iso
mkdir /mnt/iso
mkdir /tmp/working_directory
mount -o loop /tmp/rl9.iso /mnt/iso
rsync -av /mnt/iso/* /tmp/working_directory
umount /mnt/iso
cat <<EOF > /tmp/working_directory/isolinux/isolinux.cfg
UI menu.c32
PROMPT 0
TIMEOUT 100
DEFAULT local

MENU TITLE Nexigen SOC Bootloader
MENU AUTOBOOT Booting local disk in # seconds

LABEL local
  MENU LABEL Boot Local Disk
  menu default
  localboot 0xffff

LABEL vulnscanner
  MENU LABEL Install Vuln Scanner
  kernel vmlinuz
  append initrd=initrd.img inst.stage2=hd:LABEL=Rocky-9-4-x86_64-dvd inst.ks=https://raw.githubusercontent.com/CriticalWombat/KickScan/dev/ks.cfg quiet
EOF
mkisofs -o /tmp/GB_Vuln.iso -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -R -J -v -T -V "Rocky-9-4-x86_64-dvd" /tmp/working_directory
